language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export TZ="America/Sao_Paulo"
notifications:
  email: false
node_js:
  - '10'
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
