// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

var output = /* () */0;

exports.output = output;
/*  Not a pure module */
