// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Demo$Crop = require("../src/Demo.bs.js");

describe("Demo", (function () {
        return Jest.test("output", (function () {
                      return Jest.Expect[/* toBe */2](/* () */0, Jest.Expect[/* expect */0](Demo$Crop.output));
                    }));
      }));

/*  Not a pure module */
